MinioConfig:
  Endpoint: "play.minio.io:9000"
  AccessKeyID: "Q3AM3UQ867SPQQA43P2F"
  SecretAccessKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  # Endpoint: "s3.amazonaws.com"
  # AccessKeyID: "AKIAIFYKTDXJKWOLQR5Q"
  # SecretAccessKey: "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"
  UseSSL: true

BucketConfig:
  BucketName: "yabs"
  Location: "us-east-1"

FileConfig:
  ObjectName: "test.txt.zip"
  FilePath: "storage/tmp/test.txt.zip"
  ContentType: "application/zip"