MinioConfig:
  Endpoint: "play.minio.io:9000"
  AccessKeyID: "Q3AM3UQ867SPQQA43P2F"
  SecretAccessKey: "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"
  BucketName: "yabs"
  Location: "us-east-1"
  UseSSL: true

FileConfig:
  ObjectName: "test.txt.zip"
  FilePath: "storage/tmp/test.txt.zip"
  ContentType: "application/zip"

GoogleConfig:
  BucketName: "yabs"
  ProjectID: "tactile-carver-230508"